import '../map_screen/widgets/listcalendar_item_widget.dart';import '../map_screen/widgets/listsearch_item_widget.dart';import 'controller/map_controller.dart';import 'models/listcalendar_item_model.dart';import 'models/listsearch_item_model.dart';import 'package:alli_s_application8/core/app_export.dart';import 'package:alli_s_application8/widgets/app_bar/appbar_image.dart';import 'package:alli_s_application8/widgets/app_bar/appbar_subtitle_5.dart';import 'package:alli_s_application8/widgets/app_bar/custom_app_bar.dart';import 'package:alli_s_application8/widgets/custom_outlined_button.dart';import 'package:flutter/material.dart';class MapScreen extends GetWidget<MapController> {const MapScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.primary, appBar: CustomAppBar(height: getVerticalSize(44), leadingWidth: 28, leading: AppbarImage(height: getVerticalSize(14), width: getHorizontalSize(8), svgPath: ImageConstant.imgArrowleftGray80001, margin: getMargin(left: 20, top: 12, bottom: 17), onTap: () {onTapArrowleft3();}), centerTitle: true, title: AppbarSubtitle5(text: "lbl_nurse_search".tr), actions: [CustomOutlinedButton(text: "lbl_cancel".tr, margin: getMargin(left: 20, top: 2, right: 20, bottom: 2), buttonStyle: ButtonThemeHelper.outlinePinkA100.copyWith(fixedSize: MaterialStateProperty.all<Size>(Size(getHorizontalSize(65), getVerticalSize(39)))), buttonTextStyle: TextThemeHelper.titleSmallGray60002)]), body: SizedBox(width: size.width, child: SingleChildScrollView(padding: getPadding(top: 21), child: Padding(padding: getPadding(right: 4), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Padding(padding: getPadding(left: 20), child: Text("lbl_quick_filter".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: theme.textTheme.titleSmall)), Align(alignment: Alignment.center, child: Padding(padding: getPadding(left: 20, top: 8, right: 16), child: Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: getVerticalSize(20));}, itemCount: controller.mapModelObj.value.listcalendarItemList.value.length, itemBuilder: (context, index) {ListcalendarItemModel model = controller.mapModelObj.value.listcalendarItemList.value[index]; return ListcalendarItemWidget(model);})))), Padding(padding: getPadding(left: 20, top: 31), child: Text("lbl_filter_by".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: theme.textTheme.titleSmall)), Align(alignment: Alignment.center, child: Padding(padding: getPadding(left: 20, top: 7, right: 11), child: Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: getVerticalSize(20));}, itemCount: controller.mapModelObj.value.listsearchItemList.value.length, itemBuilder: (context, index) {ListsearchItemModel model = controller.mapModelObj.value.listsearchItemList.value[index]; return ListsearchItemWidget(model);})))), GestureDetector(onTap: () {onTapColumnapply();}, child: Container(margin: getMargin(top: 20), padding: getPadding(left: 16, top: 10, right: 16, bottom: 10), decoration: AppDecoration.white, child: CustomOutlinedButton(text: "lbl_apply_filter".tr, buttonStyle: ButtonThemeHelper.outlineBluegray10002.copyWith(fixedSize: MaterialStateProperty.all<Size>(Size(double.maxFinite, getVerticalSize(59)))), buttonTextStyle: TextThemeHelper.titleSmallGray90004)))])))))); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] library to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleft3() { Get.back(); } 
/// Navigates to the upcomingBookingFiveScreen when the action is triggered.

/// When the action is triggered, this function uses the `Get` package to
/// push the named route for the upcomingBookingFiveScreen.
onTapColumnapply() { Get.toNamed(AppRoutes.upcomingBookingFiveScreen, ); } 
 }
