import '../pack_detail_composer_screen/widgets/listtitle_item_widget.dart';import 'controller/pack_detail_composer_controller.dart';import 'models/listtitle_item_model.dart';import 'package:alli_s_application8/core/app_export.dart';import 'package:alli_s_application8/widgets/custom_bottom_bar.dart';import 'package:alli_s_application8/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';class PackDetailComposerScreen extends GetWidget<PackDetailComposerController> {const PackDetailComposerScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: appTheme.pinkA100, body: SizedBox(width: double.maxFinite, child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Container(width: double.maxFinite, padding: getPadding(left: 4, top: 30, right: 4, bottom: 30), decoration: AppDecoration.brand, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.end, children: [Padding(padding: getPadding(left: 12, top: 17, bottom: 5), child: Text("lbl_composer".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: theme.textTheme.displaySmall)), CustomElevatedButton(text: "lbl_go_to_dashboard".tr, margin: getMargin(top: 18), buttonStyle: ButtonThemeHelper.fillBluegray90003.copyWith(fixedSize: MaterialStateProperty.all<Size>(Size(getHorizontalSize(148), getVerticalSize(52)))), buttonTextStyle: TextThemeHelper.titleSmallPrimary_1, onTap: () {onTapGotodashboard();})])), Expanded(child: Padding(padding: getPadding(top: 10), child: Obx(() => ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: getVerticalSize(17));}, itemCount: controller.packDetailComposerModelObj.value.listtitleItemList.value.length, itemBuilder: (context, index) {ListtitleItemModel model = controller.packDetailComposerModelObj.value.listtitleItemList.value[index]; return ListtitleItemWidget(model);}))))])), bottomNavigationBar: CustomBottomBar(onChanged: (BottomBarEnum type) {}))); } 
/// Navigates to the upcomingBookingTwoScreen when the action is triggered.

/// When the action is triggered, this function uses the `Get` package to
/// push the named route for the upcomingBookingTwoScreen.
onTapGotodashboard() { Get.toNamed(AppRoutes.upcomingBookingTwoScreen, ); } 
 }
