import 'controller/upcoming_booking_six_controller.dart';import 'package:alli_s_application8/core/app_export.dart';import 'package:alli_s_application8/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';class UpcomingBookingSixScreen extends GetWidget<UpcomingBookingSixController> {const UpcomingBookingSixScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.primary, body: Container(width: double.maxFinite, padding: getPadding(top: 12, bottom: 12), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Text("lbl_payment".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: TextThemeHelper.titleMediumBold), Spacer(), CustomImageView(svgPath: ImageConstant.imgCheckmarkPinkA100, height: getSize(40), width: getSize(40)), Padding(padding: getPadding(top: 13), child: Text("msg_booking_successful".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: TextThemeHelper.headlineSmallGray80001)), Padding(padding: getPadding(top: 8, bottom: 266), child: Text("msg_your_appointment".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: TextThemeHelper.bodyMediumGray8000114))])), bottomNavigationBar: Container(margin: getMargin(left: 20, right: 19, bottom: 16), decoration: AppDecoration.white, child: CustomElevatedButton(text: "lbl_next".tr, buttonStyle: ButtonThemeHelper.fillPinkA100.copyWith(fixedSize: MaterialStateProperty.all<Size>(Size(double.maxFinite, getVerticalSize(53)))), buttonTextStyle: TextThemeHelper.titleSmallPrimary_1, onTap: () {onTapNext();})))); } 
/// Navigates to the usageFollowUpNegativeSelectionScreen when the action is triggered.

/// When the action is triggered, this function uses the `Get` package to
/// push the named route for the usageFollowUpNegativeSelectionScreen.
onTapNext() { Get.toNamed(AppRoutes.usageFollowUpNegativeSelectionScreen, ); } 
 }
