import 'controller/upcoming_booking_controller.dart';import 'package:alli_s_application8/core/app_export.dart';import 'package:alli_s_application8/widgets/app_bar/appbar_image.dart';import 'package:alli_s_application8/widgets/app_bar/appbar_subtitle_5.dart';import 'package:alli_s_application8/widgets/app_bar/custom_app_bar.dart';import 'package:alli_s_application8/widgets/custom_drop_down.dart';import 'package:flutter/material.dart';class UpcomingBookingScreen extends GetWidget<UpcomingBookingController> {const UpcomingBookingScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.primary, appBar: CustomAppBar(height: getVerticalSize(49), leadingWidth: 29, leading: AppbarImage(height: getVerticalSize(15), width: getHorizontalSize(9), svgPath: ImageConstant.imgArrowleftGray80001, margin: getMargin(left: 20, top: 15, bottom: 19), onTap: () {onTapArrowleft5();}), centerTitle: true, title: AppbarSubtitle5(text: "lbl_support".tr)), body: Container(width: double.maxFinite, padding: getPadding(top: 15, bottom: 15), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Container(width: double.maxFinite, padding: getPadding(left: 20, top: 9, right: 20, bottom: 9), decoration: AppDecoration.outline8, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("msg_how_to_delete_account".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: theme.textTheme.titleMedium), CustomImageView(svgPath: ImageConstant.imgArrowdownGray80001, height: getSize(18), width: getSize(18), margin: getMargin(top: 2, bottom: 2))])), Container(width: double.maxFinite, margin: getMargin(top: 20), padding: getPadding(left: 20, top: 8, right: 20, bottom: 8), decoration: AppDecoration.outline8, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: getPadding(top: 3), child: Text("msg_how_do_i_delete".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: theme.textTheme.titleMedium)), CustomImageView(svgPath: ImageConstant.imgArrowdownGray80001, height: getSize(18), width: getSize(18), margin: getMargin(top: 3, bottom: 3))])), CustomDropDown(focusNode: FocusNode(), autofocus: true, icon: Container(margin: getMargin(left: 30, right: 19), child: CustomImageView(svgPath: ImageConstant.imgArrowdownGray80001)), hintText: "msg_i_don_t_need_notifications".tr, margin: getMargin(top: 20), textStyle: theme.textTheme.titleMedium!, items: controller.upcomingBookingModelObj.value.dropdownItemList.value, contentPadding: getPadding(left: 20, top: 10, bottom: 10), onChanged: (value) {controller.onSelected(value);}), CustomDropDown(focusNode: FocusNode(), autofocus: true, icon: Container(margin: getMargin(left: 30, right: 20), child: CustomImageView(svgPath: ImageConstant.imgArrowdownGray80001)), hintText: "msg_how_to_download".tr, margin: getMargin(top: 20, bottom: 5), textStyle: theme.textTheme.titleMedium!, items: controller.upcomingBookingModelObj.value.dropdownItemList1.value, contentPadding: getPadding(left: 20, top: 10, bottom: 10), onChanged: (value) {controller.onSelected1(value);})])))); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] library to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleft5() { Get.back(); } 
 }
